version: "3.9"
services:
  web:
    build: .
    networks:
        - app-tier
    ports:
      - "80:5000"
  redis:
    image: "redis:alpine"
    networks:
      - app-tier
    ports:
      - "6379"
networks:
  app-tier:
    driver: bridge